export const DEFAULT_WEB3_SERVER = 'ws://0.0.0.0:7545';
export const INFURA_IPFS_PROJECT_ID = process.env.REACT_APP_INFURA_IPFS_PROJECT_ID
export const INFURA_IPFS_PROJECT_SECRET = process.env.REACT_APP_INFURA_IPFS_PROJECT_SECRET
